export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const DEVICE_ROUTE = '/device'
export const EDIT_ROUTE = '/edit'
export const ABOUT_ROUTE = '/about-us'